### ISSUE TITLE
Pow64 function weirdness

### ISSUE THREAD

**Issue by bzed** [davidcoles/xvs#2]
Hi,

we were looking at
https://github.com/davidcoles/xvs/blob/26bd96bdc5226ba52f26c62fabe4d927c580f701/bpf/bpf.go#L18C1-L150C2

and wondering, what the reason behind the function is and why its using case statements instead of

```
func Pow64(x int) uint64 {
	if x < 0 || x > 64 {
		return 0
	}
	return 1 << x
}
```

cheers,

Bernd

**Comment by davidcoles** [comment]
Hello.

I think that at the time I was just trying to visualise the output and the switch/case approach was easier for me to do so, and so I could cut and paste the same code into both C/eBPF and Go.

But absolutely fair point, and I can update it to be more sensible, as per your snippet.

I don't think that code really gets used unless you are blocking IP ranges - an experimental feature that isn't used the main vc5 project yet.

Oh, I think that "x > 64" should be "x > 63", but that's a very minor quibble.

Thanks for taking the time to look at the code :-)

David

**Comment by bzed** [comment]
Ah yes of cource > 63.

If its used for blocking IP ranges, a bit more generic approach to handle v4 and v6 would make sense I guess

**Comment by davidcoles** [comment]
Yes, that's all a bit of a TODO ...

I was mostly just interested in potentially get some stats out for where traffic was coming from (eg. for a visualisation like https://raw.githubusercontent.com/davidcoles/hilbert/master/hilbert.png), and thought that it would come in useful to be able to block abusive ranges during a DDoS based on their traffic history.

**Comment by davidcoles** [comment]
Oops, accidentally closed this by including a "resolves" link in the commit message!

Anyway, I have updated the code and actually written a test for once which uses the old switch/case code to verify the function:

https://github.com/davidcoles/xvs/commit/8b657ce5b8c76cc5ed981b6ea799a59020235821

**Comment by davidcoles** [comment]
I'll close in a couple of days if there are no objections.
